### PR TITLE
Windows path separator 

### LINKED ISSUE #68: Release 5.3.3 introduce bug on Windows with base Path
Hi, 

Before release 5.3.3 and this commit https://github.com/gulpjs/glob-stream/commit/4a01f00b8bf991c892e77c4635884e1eb30705fc, basePath ended with a ```path.sep```.
And now this behavior has moved to the ```getBasePath``` function which lost the ```path.sep```.

On Windows, many gulp plugin not work anymore since this release.

### PR DESCRIPTION
**Pull request by doowb**
This PR includes the following changes:

- Add appveyor configuration file
- Use `.` pattern for jscs for windows.
- Handle windows path separators when calculating base path on windows.

This fixes #68

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -190,7 +191,19 @@ function globIsSingular(glob) {
 }
 
 function getBasePath(ourGlob, opt) {
-  return resolveGlob(globParent(ourGlob) + path.sep, opt);
+  var basePath;
+  var parent = globParent(ourGlob);
+
+  if (parent === '/' && opt && opt.root) {
+    basePath = path.join(opt.root);
```
Comment (phated) [inline index.js]: would this be `path.normalize` since you aren't joining anything?

File: index.js [hunk 2]
```diff
@@ -190,7 +191,19 @@ function globIsSingular(glob) {
...
+  } else {
+    basePath = resolveGlob(parent, opt);
+  }
+
+  if (!sepRe.test(basePath.charAt(basePath.length - 1))) {
```
Comment (phated) [inline index.js]: Is it better to use `charAt` than access the last element like an array?

File: index.js [hunk 3]
```diff
@@ -10,6 +10,7 @@ var resolveGlob = require('to-absolute-glob');
 var globParent = require('glob-parent');
 var path = require('path');
 var extend = require('extend');
+var sepRe = (process.platform === 'win32' ? /[\/\\]/ : /\/+/);
```
Comment (phated) [inline index.js]: can this be `new RegExp(path.sep)`?

Comment (doowb) [inline index.js]: For `win32` it's checking for either `/` or `\` and replacing with the `path.sep`. This is because the user might have passed in `/` on windows in their glob pattern.

File: index.js (hunk 1 above)
Comment (doowb) [inline index.js]: Yeah, `.normalize` would be better. I'll change that.

File: index.js (hunk 2 above)
Comment (phated) [inline index.js]: Is testing the last character better than a `$` in the RegExp?

Comment (doowb) [inline index.js]: I think this is more habit for me with strings since it differentiates them from other arrays. I also read that it was faster in node.

Comment (doowb) [inline index.js]: > Is testing the last character better than a $ in the RegExp?

I think so because I don't think regex will start from the end of a string and test backwards so it'll be testing all the possible combinations leading up to the end. By only testing the last character, it reduces the amount of characters that the regex has to go through.

Comment (phated) [inline index.js]: That's weird that RegExps with the "ends with" character would search the whole string.

Comment (doowb) [inline index.js]: > search the whole string

I thought that too, but [this talk](https://vimeo.com/112065252) is where I learned more about regexp. I'm assuming that it works this way when using `$` too because the regexp compiler would need match patterns leading up to the `$`.

If I find the time, I may put together some benchmarks with these patterns.

**Comment by phated** [comment]
LGTM :shipit:

**Comment by phated** [comment]
Published as 5.3.4 - thanks again @doowb!
